Wesley validacoes
ifrn-pdcorp/sea pull request #44
Opened 2020-11-10 01:57 UTC by WesleyDev01

01. Foram adicionadas as opções de download e upload de arquivos.
02. Para fazer upload de arquivos o usuário não pode ser estudante. Foram adicionadas validações para verificar se o evento existe no banco de dados, se a atividade existe no evento e se o usuário não é estudante.
03. Para fazer download de arquivos o usuário precisa estar cadastrado no evento.
04. Foram adicionadas as informações de contato no swagger referentes ao nome do grupo e o e-mail.
05. Para adicionar um novo evento agora é feito a verificação se o usuário não é um estudante.

2020-11-16 11:19 UTC, dannylo reviewed
- Padrão de URL para upload não está de acordo com o esperado pelo REST, talvez um event/{idEvent}/activity/{idActivity}/uploadFile sejá melhor.
- Download a mesma coisa. Porque o Dowload requer idSubscription e upload não? Nâo entendi isso.
- catch de exceptions não fazem nada?  Isso não pode acontecer, sempre deve ter alguma reação do sistema a uma exception, como o usuário saberá do ocorrido?

- Porque os endpoints de arquivos para uma atividade estão no controller de evento quando deveriam estar no de atividade? Não é um coisa da atividade esses arquivos?

- Não entendi o que é esse UploadFileResponse, ele não deveria ser um modelo?
- O construtor EventService vai sempre criar os diretórios? Ou ele só cria quando não existe um? Isso foi testado?
- Não vi em nenhum arquivo a associação da atividade aos seus materiais? Como uma atividade vai saber quais são os seus materiais? Isso não foi setado.

2020-11-17 11:16 UTC, dannylo reviewed
- Já existe um arquivo java para lidar com configs de upload.

2020-12-16 09:35 UTC, WesleyDev01 commented
1 - Padrão de URL alterado de acordo com o REST em ambos os métodos (upload e download)
2 - Para fazer upload do arquivo vai haver uma verificação se o evento existe e se a atividade escolhida está associada aquele evento
3 - Usuários alunos agora não podem criar eventos
4 - Está liberado o upload para todos os usuários com exceção dos alunos
5 - Agora os catchs que antes estavam vazios possuem retorno
6 - Os endpoints da atividade permanecem no controller do evento pois ainda não há um específico para as atividades
7 - Métodos que antes estavam no serviço de evento foram trocados para o serviço de atividades
8 - Modelo de arquivos criado
9 - O diretório dos arquivos sempre será criado caso ele não exista e quando existir fará somente o upload normal, tanto dos arquivos como das imagens (já foi testado)
10 - Informações dos arquivos são guardadas no banco de dados, porém os arquivos em si serão armazenados fora do banco
11 - Agora há uma associação entre os arquivos e suas respectivas atividades

2020-12-22 10:49 UTC, dannylo requested changes

2020-12-22 10:49 UTC, dannylo commented on backend/api-sea/src/main/java/br/edu/ifrn/laj/pdcorp/apisea/services/ActivityService.java
> +	public Object saveFileDb(String fileName, String fileType, long fileSize, long idActivity) {
Porque não criar um DTO para esses parâmetros? Eles soltos não são uma boa prática.

2020-12-22 11:41 UTC, dannylo commented on backend/api-sea/src/main/java/br/edu/ifrn/laj/pdcorp/apisea/services/ActivityService.java
> +	public Object saveFileDb(String fileName, String fileType, long fileSize, long idActivity) {
Object não é um bom retorno.

2021-01-05 11:05 UTC, dannylo approved these changes

2021-01-05 11:06 UTC, merged